### ISSUE TITLE
Running TestTrix

### ISSUE THREAD

**Issue by Atunez** [AgileAppstate/javatrix-eigentrix#1]
Running the starter test code.

Finish the following issues:

- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/10
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/2
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/3
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/4
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/5
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/6
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/7
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/8
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/9
- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/11
